//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int Id { get; set; }
        public int AppartmentId { get; set; }
        public string Message { get; set; }
        public bool ToAdmin { get; set; }
        public bool DeletedByAdmin { get; set; }
        public bool DeletedByUser { get; set; }
    
        public virtual Appartments Appartments { get; set; }
    }
}
