//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TarsashazDBEntities : DbContext
    {
        public TarsashazDBEntities()
            : base("name=TarsashazDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appartments> Appartments { get; set; }
        public virtual DbSet<BuildingInvoices> BuildingInvoices { get; set; }
        public virtual DbSet<Invoices> Invoices { get; set; }
        public virtual DbSet<MainMeters> MainMeters { get; set; }
        public virtual DbSet<Meters> Meters { get; set; }
        public virtual DbSet<Readings> Readings { get; set; }
        public virtual DbSet<Services> Services { get; set; }
    }
}
